[build-system]
requires = ["setuptools>=82.0.1", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mesouq"
version = "0.1.0"
description = "Bayesian uncertainty quantification and calibration of mesoscopic DPD models"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
  {name = "Brieuc Benvegnen"}
]
keywords = ["bayesian-inference", "uncertainty-quantification", "dpd", "mesoscopic-models", "hierarchical-bayesian-inference"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Topic :: Scientific/Engineering"
]

dependencies = [
  "numpy>=2.2.6",
  "pyyaml>=6.0.3",
  "pydantic>=2.12.5",
  "trimesh>=4.11.5",
]

[project.optional-dependencies]
plot = [
  "matplotlib>=3.10.8",
  "pandas>=2.3.3",
]
surrogate = [
  "pandas>=2.3.3",
  "scipy>=1.15.3",
  "torch>=2.11.0",
]
sensitivity = [
  "SALib>=1.5.2",
  "pandas>=2.3.3",
  "scipy>=1.15.3",
  "torch>=2.11.0",
]
mpi = [
  "mpi4py>=4.1.1",
]
test = [
  "SALib>=1.5.2",
  "build>=1.4.3",
  "coverage[toml]>=7.13.5",
  "matplotlib>=3.10.8",
  "pandas>=2.3.3",
  "pytest>=9.0.3",
  "scipy>=1.15.3",
  "torch>=2.11.0",
]
ci = [
  "SALib>=1.5.2",
  "build>=1.4.3",
  "matplotlib>=3.10.8",
  "pandas>=2.3.3",
  "pytest>=9.0.3",
  "scipy>=1.15.3",
  "torch>=2.11.0",
]
dev = [
  "SALib>=1.5.2",
  "build>=1.4.3",
  "coverage[toml]>=7.13.5",
  "matplotlib>=3.10.8",
  "pandas>=2.3.3",
  "pytest>=9.0.3",
  "scipy>=1.15.3",
  "torch>=2.11.0",
  "mpi4py>=4.1.1",
]

[project.urls]
Repository = "https://github.com/BrieucB/MesoUQ"
Issues = "https://github.com/BrieucB/MesoUQ/issues"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["meso_uq*"]

[tool.pytest.ini_options]
addopts = ["-ra", "--tb=short"]
testpaths = ["tests"]
