"""Inference setup helpers."""

from .contracts import (
    InferenceContract,
    InferenceLayer,
    InferenceSupportState,
    LikelihoodComponentContract,
    PosteriorArtifactContract,
    PosteriorStorageKind,
    PriorContract,
    SamplerBackendContract,
    unsupported_gv_inference_contract,
)
from .gv_hbi import (
    GV_HBI_EXPERIMENTAL_FLAG,
    GV_PHASE1_EXECUTION_MANIFEST,
    build_gv_phase1_setup_manifest,
    run_gv_phase1_dnn_execution,
    write_gv_phase1_execution_manifest,
    write_gv_phase1_setup_manifest,
)
from .posterior_equivalence import (
    DEFAULT_POSTERIOR_EQUIVALENCE_THRESHOLDS,
    PosteriorEquivalenceReport,
    PosteriorEquivalenceThresholds,
    PosteriorSummary,
    compare_posterior_samples,
    compare_posterior_summaries,
    load_phase2_posterior_samples,
    summarize_posterior_samples,
)
from .native_cuda_performance import (
    DEFAULT_NATIVE_CUDA_PERFORMANCE_THRESHOLDS,
    NativeCudaPerformanceReport,
    NativeCudaPerformanceThresholds,
    NativeCudaProfileSummary,
    check_native_cuda_profile,
    compare_native_cuda_profile,
    load_native_cuda_profile_records,
    summarize_native_cuda_profile,
)

__all__ = [
    "DEFAULT_POSTERIOR_EQUIVALENCE_THRESHOLDS",
    "DEFAULT_NATIVE_CUDA_PERFORMANCE_THRESHOLDS",
    "GV_HBI_EXPERIMENTAL_FLAG",
    "GV_PHASE1_EXECUTION_MANIFEST",
    "InferenceContract",
    "InferenceLayer",
    "InferenceSupportState",
    "LikelihoodComponentContract",
    "NativeCudaPerformanceReport",
    "NativeCudaPerformanceThresholds",
    "NativeCudaProfileSummary",
    "PosteriorArtifactContract",
    "PosteriorEquivalenceReport",
    "PosteriorEquivalenceThresholds",
    "PosteriorStorageKind",
    "PosteriorSummary",
    "PriorContract",
    "SamplerBackendContract",
    "build_gv_phase1_setup_manifest",
    "check_native_cuda_profile",
    "compare_native_cuda_profile",
    "compare_posterior_samples",
    "compare_posterior_summaries",
    "load_phase2_posterior_samples",
    "load_native_cuda_profile_records",
    "run_gv_phase1_dnn_execution",
    "summarize_posterior_samples",
    "summarize_native_cuda_profile",
    "unsupported_gv_inference_contract",
    "write_gv_phase1_execution_manifest",
    "write_gv_phase1_setup_manifest",
]
