"""Inference setup helpers."""

from .contracts import (
    InferenceContract,
    InferenceLayer,
    InferenceSupportState,
    LikelihoodComponentContract,
    PosteriorArtifactContract,
    PosteriorStorageKind,
    PriorContract,
    SamplerBackendContract,
    unsupported_gv_inference_contract,
)
from .posterior_equivalence import (
    DEFAULT_POSTERIOR_EQUIVALENCE_THRESHOLDS,
    PosteriorEquivalenceReport,
    PosteriorEquivalenceThresholds,
    PosteriorSummary,
    compare_posterior_samples,
    compare_posterior_summaries,
    load_phase2_posterior_samples,
    summarize_posterior_samples,
)
from .native_cuda_performance import (
    DEFAULT_NATIVE_CUDA_PERFORMANCE_THRESHOLDS,
    NativeCudaPerformanceReport,
    NativeCudaPerformanceThresholds,
    NativeCudaProfileSummary,
    check_native_cuda_profile,
    compare_native_cuda_profile,
    load_native_cuda_profile_records,
    summarize_native_cuda_profile,
)

__all__ = [
    "DEFAULT_POSTERIOR_EQUIVALENCE_THRESHOLDS",
    "DEFAULT_NATIVE_CUDA_PERFORMANCE_THRESHOLDS",
    "InferenceContract",
    "InferenceLayer",
    "InferenceSupportState",
    "LikelihoodComponentContract",
    "NativeCudaPerformanceReport",
    "NativeCudaPerformanceThresholds",
    "NativeCudaProfileSummary",
    "PosteriorArtifactContract",
    "PosteriorEquivalenceReport",
    "PosteriorEquivalenceThresholds",
    "PosteriorStorageKind",
    "PosteriorSummary",
    "PriorContract",
    "SamplerBackendContract",
    "check_native_cuda_profile",
    "compare_native_cuda_profile",
    "compare_posterior_samples",
    "compare_posterior_summaries",
    "load_phase2_posterior_samples",
    "load_native_cuda_profile_records",
    "summarize_posterior_samples",
    "summarize_native_cuda_profile",
    "unsupported_gv_inference_contract",
]
