#!/usr/bin/env python3

"""
Identify the PCA breathing mode from the volume change generated by each
PCA eigenvector.

This is a standalone analysis script. It does not modify or depend on
changes to the PCA-generation script.

Required:
    --mesh
    --eigenvectors

Optional:
    --mean
    --eigenvalues

If --mean is omitted, or the supplied mean-coordinate file does not
exist, the script uses the mesh vertices as the reference coordinates.

Example
-------
python3 identify_breathing_by_volume_standalone.py \
    --mesh mesh/sphere00001.off \
    --eigenvectors eigvectors_new.txt \
    --eigenvalues eigvalues_new.txt

With saved mean coordinates:
python3 identify_breathing_by_volume_standalone.py \
    --mesh mesh/sphere00001.off \
    --mean mean_positions.txt \
    --eigenvectors eigvectors_new.txt \
    --eigenvalues eigvalues_new.txt
"""

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import trimesh


def signed_mesh_volume(vertices, faces):
    triangles = vertices[faces]
    v0 = triangles[:, 0]
    v1 = triangles[:, 1]
    v2 = triangles[:, 2]

    return float(
        np.sum(
            np.einsum(
                "ij,ij->i",
                v0,
                np.cross(v1, v2),
            )
        )
        / 6.0
    )


def load_reference(mesh_path, mean_path=None):
    mesh = trimesh.load(mesh_path, process=False)

    if not isinstance(mesh, trimesh.Trimesh):
        raise TypeError(
            f"{mesh_path} did not load as one triangular mesh."
        )

    faces = np.asarray(mesh.faces, dtype=int)
    mesh_vertices = np.asarray(mesh.vertices, dtype=float)

    if mean_path is None:
        print("No --mean file supplied; using mesh vertices as reference.")
        reference = mesh_vertices
    else:
        mean_file = Path(mean_path)

        if not mean_file.exists():
            print(
                f"Warning: {mean_path} was not found.\n"
                "Using mesh vertices as the reference coordinates instead."
            )
            reference = mesh_vertices
        else:
            reference = np.loadtxt(mean_file, dtype=float)

            if reference.ndim == 1:
                if reference.size % 3 != 0:
                    raise ValueError(
                        "Mean-coordinate file cannot be reshaped to (N, 3)."
                    )
                reference = reference.reshape(-1, 3)

    if reference.shape != mesh_vertices.shape:
        raise ValueError(
            "Reference coordinates and mesh vertices have different shapes:\n"
            f"reference: {reference.shape}\n"
            f"mesh:      {mesh_vertices.shape}"
        )

    return reference, faces


def load_eigenvectors(path, n_vertices):
    values = np.loadtxt(path, dtype=float)

    if values.ndim == 1:
        values = values.reshape(-1, 1)

    n_coordinates = 3 * n_vertices

    if values.shape[0] == n_coordinates:
        return values

    if values.shape[1] == n_coordinates:
        return values.T

    raise ValueError(
        "One eigenvector-array dimension must equal 3*N.\n"
        f"Loaded shape: {values.shape}\n"
        f"Expected coordinate count: {n_coordinates}"
    )


def load_eigenvalues(path, n_modes):
    if path is None:
        return None

    eigenvalues = np.loadtxt(path, dtype=float).reshape(-1)

    if len(eigenvalues) < n_modes:
        raise ValueError(
            f"Only {len(eigenvalues)} eigenvalues were found for "
            f"{n_modes} eigenvectors."
        )

    eigenvalues = eigenvalues[:n_modes]

    if np.any(eigenvalues < 0.0):
        raise ValueError("PCA eigenvalues must be non-negative.")

    return eigenvalues


def analyze_modes(
    reference,
    faces,
    eigenvectors,
    epsilon,
    eigenvalues=None,
):
    n_vertices = len(reference)
    n_modes = eigenvectors.shape[1]

    center = np.mean(reference, axis=0)
    radial = reference - center
    radial_norms = np.linalg.norm(radial, axis=1)

    if np.any(radial_norms == 0.0):
        raise ValueError("A reference vertex lies at the shell centroid.")

    radial_hat = radial / radial_norms[:, None]

    signed_v0 = signed_mesh_volume(reference, faces)
    v0 = abs(signed_v0)

    if v0 <= 0.0:
        raise ValueError(
            "Reference mesh has zero enclosed volume. "
            "Check that it is closed and triangulated."
        )

    dtype = [
        ("mode", int),
        ("volume_score", float),
        ("dV_dq", float),
        ("radial_fraction", float),
        ("same_sign_fraction", float),
        ("combined_score", float),
        ("rms_volume_fraction", float),
        ("V_plus", float),
        ("V_minus", float),
        ("second_order_term", float),
    ]

    results = np.zeros(n_modes, dtype=dtype)

    for mode_index in range(n_modes):
        vector = eigenvectors[:, mode_index]
        norm = np.linalg.norm(vector)

        if norm == 0.0:
            results[mode_index]["mode"] = mode_index
            for field in results.dtype.names[1:]:
                results[mode_index][field] = np.nan
            continue

        displacement = (vector / norm).reshape(n_vertices, 3)

        vertices_plus = reference + epsilon * displacement
        vertices_minus = reference - epsilon * displacement

        v_plus = signed_mesh_volume(vertices_plus, faces)
        v_minus = signed_mesh_volume(vertices_minus, faces)

        dV_dq = (v_plus - v_minus) / (2.0 * epsilon)
        volume_score = abs(dV_dq) / v0

        second_order_term = (
            v_plus + v_minus - 2.0 * signed_v0
        ) / epsilon**2

        radial_components = np.einsum(
            "ij,ij->i",
            displacement,
            radial_hat,
        )

        radial_fraction = (
            np.linalg.norm(radial_components)
            / np.linalg.norm(displacement)
        )

        positive_fraction = np.mean(radial_components > 0.0)
        negative_fraction = np.mean(radial_components < 0.0)
        same_sign_fraction = max(
            positive_fraction,
            negative_fraction,
        )

        combined_score = (
            volume_score
            * radial_fraction
            * same_sign_fraction
        )

        if eigenvalues is None:
            rms_volume_fraction = np.nan
        else:
            rms_volume_fraction = (
                abs(dV_dq)
                * np.sqrt(eigenvalues[mode_index])
                / v0
            )

        results[mode_index] = (
            mode_index,
            volume_score,
            dV_dq,
            radial_fraction,
            same_sign_fraction,
            combined_score,
            rms_volume_fraction,
            v_plus,
            v_minus,
            second_order_term,
        )

    return results, v0


def print_top(results, field, title, top):
    valid = results[np.isfinite(results[field])]
    ordered = np.sort(valid, order=field)[::-1]

    print()
    print(title)
    print("-" * 94)
    print(
        f"{'mode':>6s} "
        f"{'volume score':>16s} "
        f"{'radial':>12s} "
        f"{'same sign':>12s} "
        f"{'combined':>16s} "
        f"{'RMS volume':>16s}"
    )

    for row in ordered[:top]:
        print(
            f"{row['mode']:6d} "
            f"{row['volume_score']:16.8e} "
            f"{row['radial_fraction']:12.6f} "
            f"{row['same_sign_fraction']:12.6f} "
            f"{row['combined_score']:16.8e} "
            f"{row['rms_volume_fraction']:16.8e}"
        )


def save_results(results, output_path):
    header = (
        "mode volume_score dV_dq radial_fraction same_sign_fraction "
        "combined_score rms_volume_fraction V_plus V_minus "
        "second_order_term"
    )

    matrix = np.column_stack(
        [results[name] for name in results.dtype.names]
    )

    np.savetxt(
        output_path,
        matrix,
        header=header,
        fmt=[
            "%d",
            "%.12e",
            "%.12e",
            "%.12e",
            "%.12e",
            "%.12e",
            "%.12e",
            "%.12e",
            "%.12e",
            "%.12e",
        ],
    )


def make_plots(results, prefix):
    mode = results["mode"]

    plt.figure(figsize=(9, 5))
    plt.plot(mode, results["volume_score"], "o-")
    plt.xlabel("PCA mode index")
    plt.ylabel(r"$|dV/dq|/V_0$")
    plt.title("First-order relative volume sensitivity")
    plt.tight_layout()
    plt.savefig(
        f"{prefix}_volume_score.png",
        dpi=300,
        bbox_inches="tight",
    )
    plt.close()

    plt.figure(figsize=(9, 5))
    plt.plot(
        mode,
        results["radial_fraction"],
        "o-",
        label="Radial fraction",
    )
    plt.plot(
        mode,
        results["same_sign_fraction"],
        "s-",
        label="Same-sign fraction",
    )
    plt.xlabel("PCA mode index")
    plt.ylabel("Score")
    plt.title("Radial breathing diagnostics")
    plt.legend()
    plt.tight_layout()
    plt.savefig(
        f"{prefix}_radial_diagnostics.png",
        dpi=300,
        bbox_inches="tight",
    )
    plt.close()

    plt.figure(figsize=(9, 5))
    plt.plot(mode, results["combined_score"], "o-")
    plt.xlabel("PCA mode index")
    plt.ylabel("Combined breathing score")
    plt.title("Combined breathing-mode score")
    plt.tight_layout()
    plt.savefig(
        f"{prefix}_combined_score.png",
        dpi=300,
        bbox_inches="tight",
    )
    plt.close()

    if np.any(np.isfinite(results["rms_volume_fraction"])):
        plt.figure(figsize=(9, 5))
        plt.plot(
            mode,
            results["rms_volume_fraction"],
            "o-",
        )
        plt.xlabel("PCA mode index")
        plt.ylabel(r"$|dV/dq|\sqrt{\lambda}/V_0$")
        plt.title("RMS thermal volume contribution")
        plt.tight_layout()
        plt.savefig(
            f"{prefix}_rms_volume.png",
            dpi=300,
            bbox_inches="tight",
        )
        plt.close()


def parse_arguments():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--mesh",
        required=True,
        help="Closed triangular shell mesh, for example an OFF file.",
    )

    parser.add_argument(
        "--eigenvectors",
        required=True,
        help="PCA eigenvector text file.",
    )

    parser.add_argument(
        "--mean",
        default=None,
        help=(
            "Optional mean-coordinate file. If omitted or missing, "
            "mesh vertices are used."
        ),
    )

    parser.add_argument(
        "--eigenvalues",
        default=None,
        help="Optional PCA eigenvalue text file.",
    )

    parser.add_argument(
        "--epsilon",
        type=float,
        default=1.0e-3,
    )

    parser.add_argument(
        "--nmodes",
        type=int,
        default=70,
        help="Maximum number of PCA modes to analyze. Default: 70.",
    )

    parser.add_argument(
        "--top",
        type=int,
        default=20,
    )

    parser.add_argument(
        "--prefix",
        default="breathing_volume",
    )

    return parser.parse_args()


def main():
    args = parse_arguments()

    reference, faces = load_reference(
        args.mesh,
        args.mean,
    )

    eigenvectors = load_eigenvectors(
        args.eigenvectors,
        len(reference),
    )

    if args.nmodes <= 0:
        raise ValueError("--nmodes must be a positive integer.")

    available_modes = eigenvectors.shape[1]
    n_modes = min(args.nmodes, available_modes)
    eigenvectors = eigenvectors[:, :n_modes]

    if available_modes < args.nmodes:
        print(
            f"Requested {args.nmodes} modes, but only "
            f"{available_modes} are available. Analyzing all available modes."
        )
    else:
        print(f"Analyzing the first {n_modes} PCA modes.")

    eigenvalues = load_eigenvalues(
        args.eigenvalues,
        n_modes,
    )

    results, v0 = analyze_modes(
        reference,
        faces,
        eigenvectors,
        args.epsilon,
        eigenvalues,
    )

    output_txt = f"{args.prefix}_mode_scores.txt"
    save_results(results, output_txt)

    print(f"Reference volume: {v0:.12e}")
    print(f"Number of modes:  {len(results)}")
    print(f"Epsilon:          {args.epsilon:.12e}")

    print_top(
        results,
        "volume_score",
        "Top modes by first-order volume sensitivity",
        args.top,
    )

    print_top(
        results,
        "combined_score",
        "Top modes by combined breathing score",
        args.top,
    )

    best_volume = int(
        results[np.nanargmax(results["volume_score"])]["mode"]
    )

    best_combined = int(
        results[np.nanargmax(results["combined_score"])]["mode"]
    )

    print()
    print("Breathing-mode candidates")
    print("-------------------------")
    print(
        "Largest first-order volume sensitivity: "
        f"mode {best_volume}"
    )
    print(
        "Largest combined breathing score:       "
        f"mode {best_combined}"
    )

    make_plots(results, args.prefix)

    print()
    print(f"Saved: {output_txt}")
    print(f"Saved: {args.prefix}_volume_score.png")
    print(f"Saved: {args.prefix}_radial_diagnostics.png")
    print(f"Saved: {args.prefix}_combined_score.png")

    if eigenvalues is not None:
        print(f"Saved: {args.prefix}_rms_volume.png")


if __name__ == "__main__":
    main()
