"""Narrow public API surface for dependency-light MesoUQ package contracts."""

from meso_uq.agents import (
    classify_agent_modality_support,
    get_agent_definition,
    list_agent_definitions,
    list_agent_modalities,
    missing_dependency_requirements_for_agent,
    resolve_agent_modality,
    resolve_agent_family_identifier,
    runtime_requirements_for_agent,
    supported_modalities_for_agent,
)
from meso_uq.core import (
    AgentDefinition,
    AgentFamily,
    ArtifactReference,
    ArtifactClass,
    DatasetSourceMetadata,
    InferenceBackend,
    ManifestMetadata,
    Modality,
    ModalityDescriptor,
    ModelBackend,
    NoiseModelKind,
    Platform,
    RequirementState,
    RuntimeCapability,
    RuntimeRequirement,
    RuntimeRequirementKind,
    RunMetadata,
    SurrogateIdentifier,
    UnitSystem,
)
from meso_uq.modalities import get_modality_descriptor, list_modality_descriptors

__all__ = [
    "AgentDefinition",
    "AgentFamily",
    "ArtifactReference",
    "ArtifactClass",
    "DatasetSourceMetadata",
    "InferenceBackend",
    "ManifestMetadata",
    "Modality",
    "ModalityDescriptor",
    "ModelBackend",
    "NoiseModelKind",
    "Platform",
    "RequirementState",
    "RuntimeCapability",
    "RuntimeRequirement",
    "RuntimeRequirementKind",
    "RunMetadata",
    "SurrogateIdentifier",
    "UnitSystem",
    "classify_agent_modality_support",
    "get_agent_definition",
    "get_modality_descriptor",
    "list_agent_definitions",
    "list_agent_modalities",
    "list_modality_descriptors",
    "missing_dependency_requirements_for_agent",
    "resolve_agent_modality",
    "resolve_agent_family_identifier",
    "runtime_requirements_for_agent",
    "supported_modalities_for_agent",
]
