"""Backward-compatible Vega helpers backed by site-neutral runtime paths."""

from __future__ import annotations

import hashlib
import json
import os
import shlex
import subprocess
from pathlib import Path

from meso_uq.site_runtime import RuntimePaths as VegaPaths
from meso_uq.site_runtime import get_site_runtime_paths, resolve_repo_root

DEFAULT_VEGA_MODULES = (
    "Python/3.10.8-GCCcore-12.2.0",
    "OpenMPI/4.1.4-GCC-12.2.0",
    "CUDA/12.2.2",
    "GSL/2.7-GCC-12.2.0",
    "Eigen/3.4.0-GCCcore-12.2.0",
)
DEFAULT_VEGA_RUNTIME_MODULES = DEFAULT_VEGA_MODULES + (
    "MPFR/4.2.0-GCCcore-12.2.0",
    "GMP/6.2.1-GCCcore-12.2.0",
)
DEFAULT_VEGA_MIRHEO_MODULES = DEFAULT_VEGA_MODULES + (
    "CMake/3.24.3-GCCcore-12.2.0",
    "HDF5/1.14.0-gompi-2022b",
)
DEFAULT_MIRHEO_SOURCE_PATH = "/ceph/hpc/home/eubrieucb/software/Mirheo"
MIRHEO_LOCK_FILENAME = "mirheo.lock.json"
MIRHEO_TREE_HASH_IGNORE = {
    ".git",
    "build",
    "__pycache__",
    "Mirheo.egg-info",
}


def get_vega_paths(repo_root: str | Path | None = None) -> VegaPaths:
    return get_site_runtime_paths(repo_root, site="vega")


def get_runtime_paths(
    repo_root: str | Path | None = None,
    *,
    site: str | None = None,
    runtime_root: str | Path | None = None,
    env: dict[str, str] | None = None,
) -> VegaPaths:
    return get_site_runtime_paths(repo_root, site=site, runtime_root=runtime_root, env=env)


def split_pythonpath(value: str | None) -> list[Path]:
    if not value:
        return []
    return [Path(entry).expanduser() for entry in value.split(os.pathsep) if entry]


def _has_korali_package(path: Path) -> bool:
    package_dir = path / "korali"
    return package_dir.is_dir() or (package_dir / "__init__.py").is_file()


def find_external_korali_entries(
    current_pythonpath: str | None,
    repo_root: str | Path,
    korali_site_packages: str | Path,
) -> list[str]:
    root = Path(repo_root).expanduser().resolve()
    src_root = (root / "src").resolve()
    local_korali = Path(korali_site_packages).expanduser().resolve()
    allowed = {root, src_root, local_korali}
    external: list[str] = []
    for entry in split_pythonpath(current_pythonpath):
        resolved = entry.resolve(strict=False)
        if resolved in allowed:
            continue
        if _has_korali_package(resolved):
            external.append(str(resolved))
    return external


def build_runtime_pythonpath(
    repo_root: str | Path,
    korali_site_packages: str | Path,
    current_pythonpath: str | None = None,
    *,
    include_existing: bool = False,
) -> str:
    root = Path(repo_root).expanduser().resolve()
    src_root = (root / "src").resolve()
    local_korali = Path(korali_site_packages).expanduser().resolve()
    ordered = [local_korali, src_root, root]
    seen = {str(path) for path in ordered}

    if include_existing:
        for entry in split_pythonpath(current_pythonpath):
            resolved = entry.resolve(strict=False)
            text = str(resolved)
            if text in seen:
                continue
            if _has_korali_package(resolved):
                continue
            ordered.append(resolved)
            seen.add(text)

    return os.pathsep.join(str(path) for path in ordered)


def build_gv_runtime_pythonpath(
    repo_root: str | Path,
    gv_venv_site_packages: str | Path,
) -> str:
    root = Path(repo_root).expanduser().resolve()
    ordered: list[Path] = [
        Path(gv_venv_site_packages).expanduser().resolve(),
        root / "src",
        root,
    ]
    return os.pathsep.join(str(path) for path in ordered)


def render_korali_env_script(paths: VegaPaths) -> str:
    pythonpath = build_runtime_pythonpath(paths.repo_root, paths.korali_site_packages)
    lines = [
        "#!/usr/bin/env bash",
        f"# Generated by scripts/platforms/{paths.site}/bootstrap_korali.sh.",
        "# This intentionally replaces inherited PYTHONPATH entries so repo-local",
        "# Korali wins over any preexisting user-global installation.",
        f"export MESOUQ_SITE={shlex.quote(paths.site)}",
        f"export MESOUQ_REPO_ROOT={shlex.quote(str(paths.repo_root))}",
        f"export MESOUQ_SITE_RUNTIME_ROOT={shlex.quote(str(paths.site_root))}",
        f"export KORALI_PREFIX={shlex.quote(str(paths.korali_prefix))}",
        f"export KORALI_PYTHONPATH={shlex.quote(str(paths.korali_site_packages))}",
        f"export PYTHONPATH={shlex.quote(pythonpath)}",
    ]
    if paths.site == "vega":
        lines.insert(6, f"export MESOUQ_VEGA_ROOT={shlex.quote(str(paths.site_root))}")
    elif paths.site == "karolina":
        lines.insert(6, f"export MESOUQ_KAROLINA_ROOT={shlex.quote(str(paths.site_root))}")
    return "\n".join(lines) + "\n"


def render_gv_venv_env_script(
    paths: VegaPaths,
    *,
    source_root: str | Path,
    snapshot_path: str | Path | None = None,
) -> str:
    snapshot_text = ""
    if snapshot_path is not None:
        snapshot_text = str(Path(snapshot_path).expanduser().resolve())
    scale_space_binary = paths.site_root / "gv_cgal_tools" / "bin" / "scale_space"
    cgal_tools_root = paths.site_root / "gv_cgal_tools" / "bin"
    pythonpath = build_gv_runtime_pythonpath(
        paths.repo_root,
        gv_venv_site_packages=paths.gv_venv_site_packages,
    )
    lines = [
        "#!/usr/bin/env bash",
        f"# Generated by scripts/platforms/{paths.site}/bootstrap_mirheo.sh.",
        f"export MESOUQ_SITE={shlex.quote(paths.site)}",
        f"export MESOUQ_REPO_ROOT={shlex.quote(str(paths.repo_root))}",
        f"export MESOUQ_SITE_RUNTIME_ROOT={shlex.quote(str(paths.site_root))}",
        f"export MESOUQ_GV_VENV_ROOT={shlex.quote(str(paths.gv_venv_root))}",
        f"export MESOUQ_GV_VENV_SITE_PACKAGES={shlex.quote(str(paths.gv_venv_site_packages))}",
        f"export MESOUQ_GV_ENV_SCRIPT={shlex.quote(str(paths.gv_venv_env_script))}",
        f"export VIRTUAL_ENV={shlex.quote(str(paths.gv_venv_root))}",
        'export PATH="${MESOUQ_GV_VENV_ROOT}/bin${PATH:+:${PATH}}"',
        f"export MESOUQ_MIRHEO_SRC={shlex.quote(str(Path(source_root).expanduser().resolve()))}",
        f"export MIRHEO_SOURCE_ROOT={shlex.quote(str(Path(source_root).expanduser().resolve()))}",
        f"export MIRHEO_BUILD_DIR={shlex.quote(str(paths.mirheo_build_dir))}",
        f"export MIRHEO_INSTALL_PREFIX={shlex.quote(str(paths.mirheo_prefix))}",
        f"export PYTHONPATH={shlex.quote(pythonpath)}",
        f'if [[ -z "${{GV_SCALE_SPACE_BINARY:-}}" && -x {shlex.quote(str(scale_space_binary))} ]]; then',
        f"  export GV_SCALE_SPACE_BINARY={shlex.quote(str(scale_space_binary))}",
        "else",
        '  export GV_SCALE_SPACE_BINARY="${GV_SCALE_SPACE_BINARY:-}"',
        "fi",
        f'if [[ -z "${{GV_CGAL_TOOLS_ROOT:-}}" && -d {shlex.quote(str(cgal_tools_root))} ]]; then',
        f"  export GV_CGAL_TOOLS_ROOT={shlex.quote(str(cgal_tools_root))}",
        "else",
        '  export GV_CGAL_TOOLS_ROOT="${GV_CGAL_TOOLS_ROOT:-}"',
        "fi",
    ]
    if paths.site == "vega":
        lines.insert(4, f"export MESOUQ_VEGA_ROOT={shlex.quote(str(paths.site_root))}")
    elif paths.site == "karolina":
        lines.insert(4, f"export MESOUQ_KAROLINA_ROOT={shlex.quote(str(paths.site_root))}")
    if snapshot_text:
        lines.append(f"export MIRHEO_SOURCE_SNAPSHOT={shlex.quote(snapshot_text)}")
    lines.extend(
        [
            'if command -v mpicxx >/dev/null 2>&1; then',
            '  export MESOUQ_OPENMPI_LIB_DIR="$(dirname "$(dirname "$(command -v mpicxx)")")/lib"',
            '  if [[ -d "$MESOUQ_OPENMPI_LIB_DIR" ]]; then',
            '    case ":${LD_LIBRARY_PATH}:" in',
            '      *":${MESOUQ_OPENMPI_LIB_DIR}:"*) ;;',
            '      *) export LD_LIBRARY_PATH="${MESOUQ_OPENMPI_LIB_DIR}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}" ;;',
            "    esac",
            "  fi",
            "fi",
        ]
    )
    return "\n".join(lines) + "\n"


def load_mirheo_source_lock(repo_root: str | Path | None = None) -> dict[str, object]:
    paths = get_vega_paths(repo_root)
    if not paths.mirheo_source_lock.is_file():
        return {"source_path": DEFAULT_MIRHEO_SOURCE_PATH}
    payload = json.loads(paths.mirheo_source_lock.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"Invalid Mirheo source lock payload: {paths.mirheo_source_lock}")
    source_path = payload.get("source_path") or DEFAULT_MIRHEO_SOURCE_PATH
    payload["source_path"] = source_path
    return payload


def resolve_mirheo_source(
    repo_root: str | Path | None = None,
    *,
    override: str | Path | None = None,
) -> Path:
    if override is not None:
        return Path(override).expanduser().resolve()
    env_override = os.environ.get("MESOUQ_MIRHEO_SRC", "").strip()
    if env_override:
        return Path(env_override).expanduser().resolve()
    lock = load_mirheo_source_lock(repo_root)
    return Path(str(lock["source_path"])).expanduser().resolve()


def _git_output(source_root: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(source_root), *args],
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        return ""
    return (result.stdout or "").strip()


def _iter_mirheo_source_files(source_root: Path):
    for path in sorted(source_root.rglob("*")):
        if not path.is_file():
            continue
        if any(part in MIRHEO_TREE_HASH_IGNORE for part in path.parts):
            continue
        yield path


def gather_mirheo_source_snapshot(source_root: str | Path) -> dict[str, object]:
    root = Path(source_root).expanduser().resolve()
    digest = hashlib.sha256()
    file_count = 0
    total_bytes = 0
    for path in _iter_mirheo_source_files(root):
        rel = path.relative_to(root).as_posix()
        digest.update(rel.encode("utf-8"))
        digest.update(b"\0")
        data = path.read_bytes()
        digest.update(data)
        digest.update(b"\0")
        file_count += 1
        total_bytes += len(data)
    git_commit = _git_output(root, "rev-parse", "HEAD")
    git_remote = _git_output(root, "remote", "get-url", "origin")
    return {
        "source_root": str(root),
        "tree_sha256": digest.hexdigest(),
        "file_count": file_count,
        "total_bytes": total_bytes,
        "git_commit": git_commit or None,
        "git_remote": git_remote or None,
    }


def render_mirheo_env_script(
    paths: VegaPaths,
    *,
    source_root: str | Path,
    snapshot_path: str | Path | None = None,
) -> str:
    snapshot_text = ""
    if snapshot_path is not None:
        snapshot_text = str(Path(snapshot_path).expanduser().resolve())
    lines = [
        "#!/usr/bin/env bash",
        f"# Generated by scripts/platforms/{paths.site}/bootstrap_mirheo.sh.",
        f"export MESOUQ_SITE={shlex.quote(paths.site)}",
        f"export MESOUQ_REPO_ROOT={shlex.quote(str(paths.repo_root))}",
        f"export MESOUQ_SITE_RUNTIME_ROOT={shlex.quote(str(paths.site_root))}",
        f"export MESOUQ_MIRHEO_SRC={shlex.quote(str(Path(source_root).expanduser().resolve()))}",
        f"export MIRHEO_SOURCE_ROOT={shlex.quote(str(Path(source_root).expanduser().resolve()))}",
        f"export MIRHEO_BUILD_DIR={shlex.quote(str(paths.mirheo_build_dir))}",
        f"export MIRHEO_INSTALL_PREFIX={shlex.quote(str(paths.mirheo_prefix))}",
    ]
    if paths.site == "vega":
        lines.insert(4, f"export MESOUQ_VEGA_ROOT={shlex.quote(str(paths.site_root))}")
    elif paths.site == "karolina":
        lines.insert(4, f"export MESOUQ_KAROLINA_ROOT={shlex.quote(str(paths.site_root))}")
    if snapshot_text:
        lines.append(f"export MIRHEO_SOURCE_SNAPSHOT={shlex.quote(snapshot_text)}")
    return "\n".join(lines) + "\n"


def render_tinytex_env_script(paths: VegaPaths) -> str:
    lines = [
        "#!/usr/bin/env bash",
        f"# Generated by scripts/platforms/{paths.site}/bootstrap_tex.sh.",
        f"export MESOUQ_SITE={shlex.quote(paths.site)}",
        f"export MESOUQ_REPO_ROOT={shlex.quote(str(paths.repo_root))}",
        f"export MESOUQ_SITE_RUNTIME_ROOT={shlex.quote(str(paths.site_root))}",
        f"export MESOUQ_TINYTEX_ROOT={shlex.quote(str(paths.tinytex_root))}",
        f"export PATH={shlex.quote(str(paths.tinytex_bin_dir))}:$PATH",
    ]
    if paths.site == "vega":
        lines.insert(4, f"export MESOUQ_VEGA_ROOT={shlex.quote(str(paths.site_root))}")
    elif paths.site == "karolina":
        lines.insert(4, f"export MESOUQ_KAROLINA_ROOT={shlex.quote(str(paths.site_root))}")
    return "\n".join(lines) + "\n"
