"""Helpers for repo-local Vega bootstrap and runtime paths."""

from __future__ import annotations

import os
import shlex
import sys
from dataclasses import dataclass
from pathlib import Path

DEFAULT_VEGA_MODULES = (
    "Python/3.10.8-GCCcore-12.2.0",
    "openmpi/4.1.2.1",
    "CUDA/12.2.2",
    "GSL/2.7-GCC-12.2.0",
    "Eigen/3.4.0-GCCcore-12.2.0",
)


@dataclass(frozen=True)
class VegaPaths:
    repo_root: Path
    src_root: Path
    vega_root: Path
    logs_dir: Path
    korali_source: Path
    korali_root: Path
    korali_build_dir: Path
    korali_prefix: Path
    korali_site_packages: Path
    korali_env_script: Path


def resolve_repo_root(start: str | Path | None = None) -> Path:
    current = Path(start).expanduser().resolve() if start is not None else Path(__file__).resolve()
    search_root = current if current.is_dir() else current.parent
    for candidate in (search_root, *search_root.parents):
        if (candidate / "pyproject.toml").is_file() and (candidate / "extern" / "korali").is_dir():
            return candidate
    raise FileNotFoundError("Could not locate the MesoUQ repo root from the provided path.")


def get_vega_paths(repo_root: str | Path | None = None) -> VegaPaths:
    root = resolve_repo_root(repo_root)
    vega_root = root / "_vega"
    korali_root = vega_root / "korali"
    py_tag = f"python{sys.version_info.major}.{sys.version_info.minor}"
    return VegaPaths(
        repo_root=root,
        src_root=root / "src",
        vega_root=vega_root,
        logs_dir=vega_root / "logs",
        korali_source=root / "extern" / "korali",
        korali_root=korali_root,
        korali_build_dir=korali_root / "build",
        korali_prefix=korali_root / "install",
        korali_site_packages=korali_root / "install" / "lib" / py_tag / "site-packages",
        korali_env_script=korali_root / "env.sh",
    )


def split_pythonpath(value: str | None) -> list[Path]:
    if not value:
        return []
    return [Path(entry).expanduser() for entry in value.split(os.pathsep) if entry]


def _has_korali_package(path: Path) -> bool:
    package_dir = path / "korali"
    return package_dir.is_dir() or (package_dir / "__init__.py").is_file()


def find_external_korali_entries(
    current_pythonpath: str | None,
    repo_root: str | Path,
    korali_site_packages: str | Path,
) -> list[str]:
    root = Path(repo_root).expanduser().resolve()
    src_root = (root / "src").resolve()
    local_korali = Path(korali_site_packages).expanduser().resolve()
    allowed = {root, src_root, local_korali}
    external: list[str] = []
    for entry in split_pythonpath(current_pythonpath):
        resolved = entry.resolve(strict=False)
        if resolved in allowed:
            continue
        if _has_korali_package(resolved):
            external.append(str(resolved))
    return external


def build_runtime_pythonpath(
    repo_root: str | Path,
    korali_site_packages: str | Path,
    current_pythonpath: str | None = None,
    *,
    include_existing: bool = False,
) -> str:
    root = Path(repo_root).expanduser().resolve()
    src_root = (root / "src").resolve()
    local_korali = Path(korali_site_packages).expanduser().resolve()
    ordered = [local_korali, src_root, root]
    seen = {str(path) for path in ordered}

    if include_existing:
        for entry in split_pythonpath(current_pythonpath):
            resolved = entry.resolve(strict=False)
            text = str(resolved)
            if text in seen:
                continue
            if _has_korali_package(resolved):
                continue
            ordered.append(resolved)
            seen.add(text)

    return os.pathsep.join(str(path) for path in ordered)


def render_korali_env_script(paths: VegaPaths) -> str:
    pythonpath = build_runtime_pythonpath(paths.repo_root, paths.korali_site_packages)
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by scripts/vega/bootstrap_korali.sh.",
        "# This intentionally replaces inherited PYTHONPATH entries so repo-local",
        "# Korali wins over any preexisting user-global installation.",
        f"export MESOUQ_REPO_ROOT={shlex.quote(str(paths.repo_root))}",
        f"export MESOUQ_VEGA_ROOT={shlex.quote(str(paths.vega_root))}",
        f"export KORALI_PREFIX={shlex.quote(str(paths.korali_prefix))}",
        f"export KORALI_PYTHONPATH={shlex.quote(str(paths.korali_site_packages))}",
        f"export PYTHONPATH={shlex.quote(pythonpath)}",
    ]
    return "\n".join(lines) + "\n"
