"""Active-learning contracts and dry-run engine."""

from meso_uq.active_learning.contracts import (
    AcquisitionScore,
    Candidate,
    ActiveLearningBudgetConfig,
    ActiveLearningConfig,
    ActiveLearningIterationLineage,
    ActiveLearningOutputConfig,
    ActiveLearningPlatformConfig,
    ActiveLearningRuntimeConfig,
    FailureRecord,
    LoopState,
    RetrainingRequest,
    RetrainingResult,
    SimulationRequest,
    SimulationResult,
    StoppingCriteria,
)
from meso_uq.active_learning.candidate_generation import (
    CandidateGenerationArtifacts,
    CandidateGenerationConfig,
    CandidateGenerationResult,
    CandidateParameterDimension,
    generate_candidate_batch,
    write_candidate_generation_artifacts,
)
from meso_uq.active_learning.acquisition import (
    ACQUISITION_MANIFEST_FILENAME,
    ACQUISITION_PLOT_FILENAME,
    ACQUISITION_PLOT_SIDECAR_FILENAME,
    ACQUISITION_REPORT_FILENAME,
    ACTIVE_LEARNING_ACQUISITION_ARTIFACT_SCHEMA_VERSION,
    ACTIVE_LEARNING_ACQUISITION_SCORE_SCHEMA_VERSION,
    AcquisitionScoringArtifacts,
    AcquisitionScoringConfig,
    AcquisitionScoringResult,
    SUPPORTED_POLICIES,
    score_acquisition_candidates,
    write_acquisition_artifacts,
)
from meso_uq.active_learning.constraints import (
    ActiveLearningCandidateConstraintReason,
    ActiveLearningCandidateConstraintReport,
    validate_active_learning_candidates,
)
from meso_uq.active_learning.simulation_manifest import (
    FailedSimulationQuarantineArtifacts,
    SimulationBatchManifest,
    SimulationManifestRecord,
    SubmissionBoundaryState,
    write_failed_simulation_quarantine,
)
from meso_uq.active_learning.engine import ActiveLearningDryRunEngine
from meso_uq.active_learning.result_ingestion import (
    ResultIngestionArtifacts,
    ResultIngestionBatch,
    ResultIngestionRecord,
    ingest_active_learning_results,
    write_result_ingestion_artifacts,
)

__all__ = [
    "ActiveLearningDryRunEngine",
    "AcquisitionScore",
    "Candidate",
    "ActiveLearningBudgetConfig",
    "ActiveLearningConfig",
    "ActiveLearningIterationLineage",
    "ActiveLearningOutputConfig",
    "ActiveLearningPlatformConfig",
    "ActiveLearningRuntimeConfig",
    "ActiveLearningCandidateConstraintReason",
    "ActiveLearningCandidateConstraintReport",
    "FailureRecord",
    "CandidateGenerationArtifacts",
    "CandidateGenerationConfig",
    "CandidateGenerationResult",
    "CandidateParameterDimension",
    "ACTIVE_LEARNING_ACQUISITION_ARTIFACT_SCHEMA_VERSION",
    "ACTIVE_LEARNING_ACQUISITION_SCORE_SCHEMA_VERSION",
    "ACQUISITION_MANIFEST_FILENAME",
    "ACQUISITION_PLOT_FILENAME",
    "ACQUISITION_PLOT_SIDECAR_FILENAME",
    "ACQUISITION_REPORT_FILENAME",
    "AcquisitionScoringArtifacts",
    "AcquisitionScoringConfig",
    "AcquisitionScoringResult",
    "SUPPORTED_POLICIES",
    "score_acquisition_candidates",
    "write_acquisition_artifacts",
    "LoopState",
    "RetrainingRequest",
    "RetrainingResult",
    "FailedSimulationQuarantineArtifacts",
    "SimulationBatchManifest",
    "SimulationManifestRecord",
    "SubmissionBoundaryState",
    "SimulationRequest",
    "SimulationResult",
    "StoppingCriteria",
    "generate_candidate_batch",
    "validate_active_learning_candidates",
    "write_failed_simulation_quarantine",
    "write_candidate_generation_artifacts",
    "ResultIngestionArtifacts",
    "ResultIngestionBatch",
    "ResultIngestionRecord",
    "ingest_active_learning_results",
    "write_result_ingestion_artifacts",
]
